name: CI
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  compile:
    name: Compile LavinMQ
    runs-on: ubuntu-latest
    container: 84codes/crystal:latest-ubuntu-24.04

    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y liblz4-dev

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build lavinmq
        run: make -j bin/lavinmq bin/lavinmqctl DOCS= CRYSTAL_FLAGS=-Dbake_static

      - name: Print build info
        run: bin/lavinmq --build-info

      - name: Upload bin/
        uses: actions/upload-artifact@v6
        with:
          name: bin
          path: bin/

  java-client-test:
    name: RabbitMQ java client test
    runs-on: ubuntu-24.04
    needs: compile
    continue-on-error: true

    steps:
      - name: Install LavinMQ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make openjdk-21-jre-headless liblz4-1

      - uses: actions/download-artifact@v7
        with:
          name: bin
          path: bin

      - name: Run LavinMQ in background
        run: |
          chmod +x bin/*
          bin/lavinmq --data-dir=/tmp/amqp --bind=:: &

      - name: Clone java client
        uses: actions/checkout@v6
        with:
          repository: rabbitmq/rabbitmq-java-client
          ref: v5.28.0
          path: rabbitmq-java-client

      - name: Get patch file
        uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
          path: lavinmq
          sparse-checkout: |
            .github/rabbitmq-java-client.patch
          sparse-checkout-cone-mode: false

      - name: Patch tests
        run: |
          cd rabbitmq-java-client
          git apply ../lavinmq/.github/rabbitmq-java-client.patch

      - name: Run tests
        id: test
        continue-on-error: true
        run: |
          cd rabbitmq-java-client
          make deps
          ./mvnw verify -Dtest-broker.A.nodename=lavin@testhost -Dit.test=ClientTestSuite,FunctionalTestSuite -Drabbitmqctl.bin=../bin/lavinmqctl

      - name: >-
          Test outcome: ${{ steps.test.outcome }}
        run: echo NOOP
